version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ste-strapi-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - strapi-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DATABASE_USERNAME}']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:

networks:
  strapi-network:
    driver: bridge
